# Generated by Django 5.0.6 on 2024-11-03 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoutePlot_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.BigIntegerField(unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='RoutePlot_APP.routeinfo')),
            ],
        ),
    ]
