# Generated by Django 5.0.6 on 2024-11-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoutePlot_APP', '0002_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
